# Generated by Django 4.2.2 on 2023-06-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_funcionario_remove_aluno_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
            ],
        ),
    ]
