# Generated by Django 4.2.2 on 2023-06-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('pedido', models.CharField(max_length=100)),
            ],
        ),
    ]
